import { Open_Sans } from "next/font/google";
import "./globals.css";

const openSansSemiCondensed = Open_Sans({
    variable: "--font-open-sans",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800"],
    style: ["normal", "italic"],
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={openSansSemiCondensed.className}>{children}</body>
        </html>
    );
}
